In [2]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [2]:
df = pd.read_csv('data/survey_results_public.csv')
schema_df = pd.read_csv('data/survey_results_schema.csv')

In [3]:
# df.shape
# df.info()
df.head(6)

Respondent                                         MainBranch Hobbyist  \
0           1                     I am a developer by profession      Yes   
1           2                     I am a developer by profession       No   
2           3                        I code primarily as a hobby      Yes   
3           4                     I am a developer by profession      Yes   
4           5  I used to be a developer by profession, but no...      Yes   
5           6                     I am a developer by profession       No   

    Age Age1stCode CompFreq  CompTotal  ConvertedComp             Country  \
0   NaN         13  Monthly        NaN            NaN             Germany   
1   NaN         19      NaN        NaN            NaN      United Kingdom   
2   NaN         15      NaN        NaN            NaN  Russian Federation   
3  25.0         18      NaN        NaN            NaN             Albania   
4  31.0         16      NaN        NaN            NaN       United States   
5   NaN         14      NaN        NaN            NaN             Germany   

     CurrencyDesc CurrencySymbol DatabaseDesireNextYear  \
0   European Euro            EUR   Microsoft SQL Server   
1  Pound sterling            GBP                    NaN   
2             NaN            NaN                    NaN   
3    Albanian lek            ALL                    NaN   
4             NaN            NaN       MySQL;PostgreSQL   
5   European Euro            EUR                    NaN   

                          DatabaseWorkedWith  \
0  Elasticsearch;Microsoft SQL Server;Oracle   
1                                        NaN   
2                                        NaN   
3                                        NaN   
4              MySQL;PostgreSQL;Redis;SQLite   
5                                        NaN   

                                             DevType  \
0  Developer, desktop or enterprise applications;...   
1            Developer, full-stack;Developer, mobile   
2                                                NaN   
3                                                NaN   
4                                                NaN   
5    Designer;Developer, front-end;Developer, mobile   

                                             EdLevel  \
0    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
1       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
2                                                NaN   
3    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
4       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
5  Secondary school (e.g. American high school, G...   

                                          Employment  \
0  Independent contractor, freelancer, or self-em...   
1                                 Employed full-time   
2                                                NaN   
3                                                NaN   
4                                 Employed full-time   
5                                 Employed full-time   

                      Ethnicity Gender  \
0  White or of European descent    Man   
1                           NaN    NaN   
2                           NaN    NaN   
3  White or of European descent    Man   
4  White or of European descent    Man   
5  White or of European descent    Man   

                                          JobFactors                 JobSat  \
0  Languages, frameworks, and other technologies ...     Slightly satisfied   
1                                                NaN      Very dissatisfied   
2                                                NaN                    NaN   
3  Flex time or a flexible schedule;Office enviro...  Slightly dissatisfied   
4                                                NaN                    NaN   
5  Diversity of the company or organization;Langu...     Slightly satisfied   

                                             JobSeek  \
0       I am not interested in new job opportunities   
1       I am not interested in n

In [4]:
a = np.arange(120).reshape(2, 3, 4, 5)
a

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])

In [5]:
array_4d = np.ones((1, 2, 3, 4))
array_4d

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [6]:
a = np.array([[1, 2, 3, 4, 5, 6],
              [2, 2, 3, 4, 5, 6]], dtype='int8')
a[0:2]

array([[1, 2, 3, 4, 5, 6],
       [2, 2, 3, 4, 5, 6]], dtype=int8)

In [7]:
s = pd.Series(data = range(5), index = ['A', 'B', 'C', 'D', 'E'])
s

s[[1, 2, 3]]

B    1
C    2
D    3
dtype: int64

In [11]:
df1 = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df1.to_markdown()

'|    |   0 |   1 |   2 |\n|---:|----:|----:|----:|\n|  0 |   1 |   2 |   3 |\n|  1 |   4 |   5 |   6 |\n|  2 |   7 |   8 |   9 |'